#!/bin/sh
# https://www.shellscript.sh/ lol
hi="omg"
read hi
echo "$hi it works i made my shell script!!!"
echo "ok i'll make a funny markdown file for you"
echo "# this is a markdown file generated by fard.sh" > fard.md
echo "$hi" >> fard.md
chmod 755 fard.md